prometheus:
  enabled: true

profiling:
  enabled: false
  port: 6060

logging:
  level: "info"

storage:
  data_dir: data
  gc_interval: 300
  gc_discard_ratio: 0.7

  compression: "none"
  block_cache_size: 268435456
  base_table_size: 16777216
  base_level_size: 67108864

queue:
  acknowledgement_check_interval: 1
  acknowledgement_timeout: 60
